[font]
normal = {family = "JetBrainsMono Nerd Font"}
size = 10

[window]
opacity = 0.95
decorations = "none"
dynamic_padding = true

[window.padding]
x = 5
y = 5

# [font]
# size = 10.0

# [font.normal]
# family = "Hack Nerd Font"
# style = "Regular"
#
# [colors.primary]
# background = "#000000"
# foreground = "#00FF00"

[colors.cursor]
text = "#000000"
cursor = "#00FF00"

[colors.normal]
black   = "#000000"
red     = "#FF0000"
green   = "#00FF00"
yellow  = "#FFFF00"
blue    = "#5555FF"
magenta = "#FF00FF"
cyan    = "#00FFFF"
white   = "#FFFFFF"

[colors.bright]
black   = "#555555"
red     = "#FF5555"
green   = "#55FF55"
yellow  = "#FFFF55"
blue    = "#5555FF"
magenta = "#FF55FF"
cyan    = "#55FFFF"
white   = "#FFFFFF"

[cursor.style]
shape = "underline"
blinking = "Always"
